# Generated by Django 2.0.5 on 2021-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_reg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('uname', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
