# Generated by Django 2.0.5 on 2021-03-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_upload_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_land',
            name='enc_clientid',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_clientname',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_district',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_pattanumber',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_squarefeet',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_taluk',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload_land',
            name='enc_village',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
