# Generated by Django 2.0.5 on 2021-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_upload_land_enc_clientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_product1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=300)),
                ('client_name', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('rice_name', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=300)),
                ('enc_clientname', models.CharField(max_length=300)),
                ('enc_district', models.CharField(max_length=300)),
                ('enc_ricename', models.CharField(max_length=300)),
                ('enc_quantity', models.CharField(max_length=300)),
                ('enc_amount', models.CharField(max_length=300)),
            ],
        ),
    ]
