# Generated by Django 2.0.5 on 2021-03-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_bargain11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=300)),
                ('client_name', models.CharField(max_length=300)),
                ('enc_clientname', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('originalamount', models.CharField(max_length=300)),
                ('fixedamount', models.CharField(max_length=300)),
                ('adminstatus1', models.CharField(max_length=300)),
                ('clientstatus1', models.CharField(max_length=300)),
            ],
        ),
    ]
