# Generated by Django 2.0.5 on 2021-03-04 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_bargain11'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_bargain11',
            old_name='clientstatus1',
            new_name='customerstatus1',
        ),
    ]
