# Generated by Django 2.0.5 on 2021-03-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210304_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_bargain11',
            name='cutsomerid',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer_bargain11',
            name='cutsomername',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
