# Generated by Django 2.0.5 on 2021-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210304_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_payment1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('cname', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=300)),
                ('cardno', models.CharField(max_length=300)),
                ('cvv', models.CharField(max_length=300)),
                ('holder_name', models.CharField(max_length=300)),
                ('validity', models.CharField(max_length=300)),
            ],
        ),
    ]
