# Generated by Django 2.0.5 on 2021-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_bargain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uniid', models.CharField(max_length=300)),
                ('client_id', models.CharField(max_length=300)),
                ('client_name', models.CharField(max_length=300)),
                ('enc_clientname', models.CharField(max_length=300)),
                ('pname', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=300)),
                ('amount', models.CharField(max_length=300)),
                ('status1', models.CharField(max_length=300)),
            ],
        ),
    ]
