# Generated by Django 2.0.5 on 2021-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_bargain',
            old_name='amount',
            new_name='fixedamount',
        ),
        migrations.AddField(
            model_name='client_bargain',
            name='originalamount',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
