# Generated by Django 2.0.5 on 2021-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectadmin', '0002_auto_20210302_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_bargain',
            old_name='status1',
            new_name='adminstatus1',
        ),
        migrations.AddField(
            model_name='client_bargain',
            name='clientstatus1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
